name: Lint Check

on:
  push:
    branches:
      - master
      - update_tests
    paths-ignore:
      - 'archive/**'
  pull_request:
    branches:
      - master
      - update_tests
    paths-ignore:
      - 'archive/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Delete all contents of archive/
      - name: Delete archive contents
        run: |
          rm -rf archive/*

      - uses: cclauss/Find-Python-syntax-errors-action@master
